
const generateRandomPrice = (min, max, toFix = 0) => {
    return parseFloat((Math.random() * (max - min) + min).toFixed(toFix));
}

const menuData = [
  {
    id: 1,
    name: "Paneer Butter Masala",
    price: generateRandomPrice(500, 1000),
    originalPrice: generateRandomPrice(1000, 2000),
    rating: generateRandomPrice(3, 5, 1),
    sgm: "SGM 200",
    images: ["./paneer_A.jpeg", "./paneer_B.jpeg"],
    ingredients: ["Paneer", "Tomatoes", "Butter", "Cream", "Spices"],
    description: "A rich and creamy dish made with soft paneer cubes cooked in a spicy tomato and butter sauce.",
  },
  {
    id: 2,
    name: "Hyderabadi Biryani",
    price: generateRandomPrice(500, 1000),
    originalPrice: generateRandomPrice(1000, 2000),
    rating: generateRandomPrice(3, 5, 1),
    sgm: "SGI 200",
    images: ["./hydrabadi_biryani_B.jpeg", "./hydrabadi_biryani_A.jpeg"],
    ingredients: ["Basmati Rice", "Chicken", "Spices", "Yogurt", "Saffron"],
    description: "A flavorful biryani from Hyderabad made with basmati rice, marinated chicken, and a blend of aromatic spices.",
  },
  {
    id: 3,
    name: "Masala Dosa",
    price: generateRandomPrice(500, 1000),
    originalPrice: generateRandomPrice(1000, 2000),
    rating: generateRandomPrice(3, 5, 1),
    sgm: "SGM 200",
    images: ["./masala_dosa_A.jpeg", "./masala_dosa_B.jpeg"],
    ingredients: ["Rice", "Urad Dal", "Potatoes", "Onions", "Spices"],
    description: "A crispy dosa filled with a spiced potato filling, served with chutney and sambar.",
  },
  {
    id: 4,
    name: "Chole Bhature",
    price: generateRandomPrice(500, 1000),
    originalPrice: generateRandomPrice(1000, 2000),
    rating: generateRandomPrice(3, 5, 1),
    sgm: "CGM 200",
    images: ["./bhature_A.jpeg", "./bhature_B.jpeg"],
    ingredients: ["Chickpeas", "Flour", "Tomatoes", "Onions", "Spices"],
    description: "A popular North Indian dish consisting of spicy chickpeas served with fluffy, deep-fried bread called bhature.",
  },
  {
    id: 5,
    name: "Samosa Chaat",
    price: generateRandomPrice(500, 1000),
    originalPrice: generateRandomPrice(1000, 2000),
    rating: generateRandomPrice(3, 5, 1),
    sgm: "SSM 200",
    images: ["./samosa_A.jpeg", "./samosa_B.jpeg"],
    ingredients: ["Samosa", "Chickpeas", "Yogurt", "Chutney", "Spices"],
    description: "A delightful street food made with crushed samosas, topped with tangy chutneys, yogurt, and spices.",
  },
  {
    id: 6,
    name: "Tandoori Chicken",
    price: generateRandomPrice(500, 1000),
    originalPrice: generateRandomPrice(1000, 2000),
    rating: generateRandomPrice(3, 5, 1),
    sgm: "SGM 200",
    images: ["./lobster_A.jpeg", "./lobster_B.jpeg"],
    ingredients: ["Chicken", "Yogurt", "Spices", "Ginger", "Garlic"],
    description: "A popular Indian dish where chicken is marinated in spices and yogurt, then cooked in a tandoor for a smoky flavor.",
  },
  {
    id: 7,
    name: "Pav Bhaji",
    price: generateRandomPrice(500, 1000),
    originalPrice: generateRandomPrice(1000, 2000),
    rating: generateRandomPrice(3, 5, 1),
    sgm: "SGM 200",
    images: ["./dish_M.webp", "./lobster_N.webp"],
    ingredients: ["Mixed Vegetables", "Pav Bread", "Butter", "Spices", "Lemon"],
    description: "A spicy vegetable mash served with soft buttered buns, a favorite street food from Mumbai.",
  },
  {
    id: 8,
    name: "Butter Chicken",
    price: generateRandomPrice(500, 1000),
    originalPrice: generateRandomPrice(1000, 2000),
    rating: generateRandomPrice(3, 5, 1),
    sgm: "SGM 200",
    images: ["./dish_C.webp", "./dish_A.jpeg", "./dish_B.jpeg"],
    ingredients: ["Chicken", "Tomatoes", "Butter", "Cream", "Spices"],
    description: "A creamy and mildly spiced dish made with marinated chicken cooked in a tomato and butter gravy.",
  },

  {
    id:8+ 1,
    name: "MAHN COLL OVEN",
    price: generateRandomPrice(500,1000),
    originalPrice: generateRandomPrice(1000,2000),
    rating: generateRandomPrice(3,5,1),
    sgm: "SGM 200",
    images: ["./dish_A.jpeg", "./dish_B.jpeg"],
    ingredients:["Fresh Tomatoes","Basil","Olive Oil","Sea Salt","Green Root"],
    description:
      "Doublesworn Grethellow Heo Eenex Deotent, Deotent fexis oeotre setuza ot dein ottent exues hoxtelt jhok emkoer.",
  },
  {
    id:8+ 2,
    name: "MOOUR THIENIS",
    price: generateRandomPrice(500,1000),
    originalPrice: generateRandomPrice(1000,2000),
    rating: generateRandomPrice(3,5,1),
    sgm: "SGI 200",
    images: ["./dish_B.jpeg", "./dish_A.jpeg"],
    ingredients:["Fresh Tomatoes","Basil","Olive Oil","Sea Salt","Green Root"],
    description:
      "Deotly seoty Satethellow Htew Eenoos, Deotent, Deotent fexis ototu ot deken ot seia ottent avouls hoxtelt.",
  },
  {
    id:8+ 3,
    name: "MAIN COUTCEOS",
    price: generateRandomPrice(500,1000),
    originalPrice: generateRandomPrice(1000,2000),
    rating: generateRandomPrice(3,5,1),
    sgm: "SGM 200",
    images: ["./ribeye_A.jpeg", "./ribeye_B.jpeg"],
    ingredients:["Fresh Tomatoes","Basil","Olive Oil","Sea Salt","Green Root"],
    description:
      "Doublesworn Satethellow Hteo Eenex Deotent, Deotent fexis ototu ot deken ot seia ottent avouls hoxtelt.",
  },
  {
    id:8+ 4,
    name: "PECCMN CHER CHIDRER",
    price: generateRandomPrice(500,1000),
    originalPrice: generateRandomPrice(1000,2000),
    rating: generateRandomPrice(3,5,1),
    sgm: "CGM 200",
    images: ["./pizza_A.jpeg", "./pizza_B.jpeg"],
    ingredients:["Fresh Tomatoes","Basil","Olive Oil","Sea Salt","Green Root"],
    description:
      "Deotly seoty Satethellow Htew Eenoos Deotent, Deotent fexis ototu ot deken ot seia ottent avouls hoxtelt.",
  },
  {
    id:8+ 5,
    name: "REMTANIGE OUI DUIEVER",
    price: generateRandomPrice(500,1000),
    originalPrice: generateRandomPrice(1000,2000),
    rating: generateRandomPrice(3,5,1),
    sgm: "SSM 200",
    images: ["./noodle_A.jpeg", "./noodle_B.jpeg"],
    ingredients:["Fresh Tomatoes","Basil","Olive Oil","Sea Salt","Green Root"],
    description:
      "Doublesworn Satethellow Htew Eenoos Deotent, deotent fexis ototu ot deken ot seia ottent avouls hoxtelt.",
  },
  {
    id:8+ 6,
    name: "MECRENCINITS CANCTIDUN",
    price: generateRandomPrice(500,1000),
    originalPrice: generateRandomPrice(1000,2000),
    rating: generateRandomPrice(3,5,1),
    sgm: "SGM 200",
    images: ["./lobster_A.jpeg", "./lobster_B.jpeg"],
    ingredients:["Fresh Tomatoes","Basil","Olive Oil","Sea Salt","Green Root"],
    description:
      "Doublesworn Satethellow Hteo Eenex Deotent, Deotent fexis ototu ot deken ot seia ottent avouls hoxtelt.",
  },
  {
    id:8+ 7,
    name: "MECRENCINITS CANCTIDUN",
    price: generateRandomPrice(500,1000),
    originalPrice: generateRandomPrice(1000,2000),
    rating: generateRandomPrice(3,5,1),
    sgm: "SGM 200",
    images: ["./dish_M.webp", "./lobster_N.webp"],
    ingredients:["Fresh Tomatoes","Basil","Olive Oil","Sea Salt","Green Root"],
    description:
      "Doublesworn Satethellow Hteo Eenex Deotent, Deotent fexis ototu ot deken ot seia ottent avouls hoxtelt.",
  },
  {
    id:8+ 8,
    name: "MECRENCINITS CANCTIDUN",
    price: generateRandomPrice(500,1000),
    originalPrice: generateRandomPrice(1000,2000),
    rating: generateRandomPrice(3,5,1),
    sgm: "SGM 200",
    images: ["./dish_C.webp", "./dish_A.jpeg", "./dish_B.jpeg"],
    ingredients:["Fresh Tomatoes","Basil","Olive Oil","Sea Salt","Green Root"],
    description:
      "Doublesworn Satethellow Hteo Eenex Deotent, Deotent fexis ototu ot deken ot seia ottent avouls hoxtelt.",
  },
];

export default menuData;